### ISSUE TITLE
使用 Github Actions 自动签到

### ISSUE THREAD

**Issue by savfile** [chesha1/gf2-daily-helper#1]
但是注意：

> 使用我们的服务器进行任何形式的过度自动化批量活动，通过自动化方式给我们的服务器带来不必要的负担，或通过我们的服务器中继任何形式的未经请求的广告或招揽，例如快速致富计划 [来源](https://docs.github.com/zh/site-policy/acceptable-use-policies/github-acceptable-use-policies)

可能会导致封号（甚至连坐，参考米游社自动签到），使用 [模板仓库](https://docs.github.com/zh/repositories/creating-and-managing-repositories/creating-a-template-repository) 似乎可以规避这个问题？

**Comment by chesha1** [comment]
执行自动化操作的方式好多，GitHub Actions 当然也行，考虑到大部分中国大陆的用户使用不需要外币信用卡，也没有网络问题的公有云最方便，所以我在视频里只推荐了华为云

GitHub 的用户看上去不太多所以我一开始没做，会加入开发计划的，最近写论文也比较忙，没法立即赶出来，一周内搞定吧

开发完了会在本 issue @你的

**Comment by chesha1** [comment]
@savfile 已开发完成，请查看 README，有详细的部署教程

关于你提到的封号风险，我没有太理解：
- GitHub 封号，这个是不会的，每天一次的 GitHub actions 远远达不到**过度**自动化批量活动的程度，模板仓库也不能解决这个问题，模板仓库一般是用自己或者自己组织内的模板创建新仓库，我们这里还是用 fork 比较好
- 被散爆封号，也就是你提到的米游社自动签到，这个确实是可能的，但是我也在用，我肯定首当其冲，如果真被封了肯定第一时间同步消息
- 连坐，我理解你的意思是，社区用自动签到被封号，同时游戏内账号也被封号？按理说不会这样，毕竟一个散爆账号对应多个产品，一个产品上违反协议被封了，应该不影响其他产品，在游戏里也没用脚本。我自己的亲身经历是，百度贴吧的账号被永封了，但是不影响用百度网盘。如果散爆的设计稍微成熟一点，应该不太会出现这种事，或者只要羽中的思路正常一点，不会搞连坐这一套

**Comment by chesha1** [comment]
不用担心 fork 导致原仓库和账号被封，我举一个用量比较大的例子 [ChatGPTNextWeb/ChatGPT-Next-Web](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web)

这个仓库有几万个 fork，而且都会用 GitHub Actions 自动拉取原仓库的修改，这么大的用量都没事，我们这个小仓库应该不会出事

**Comment by chesha1** [comment]
> 补充，第一次使用需要手动启用
> 
> 1. 点击仓库的 Actions，再点击 `I understand my workflows, go ahead and enable them` 启用 Actions。
> 2. 在侧边栏找到 `Scheduled Job` 并点击，再点击右侧的 `Enable workflow` 启用 Actions。

感谢提醒
