### ISSUE TITLE
不兼容邮箱登录吗

### ISSUE THREAD

**Issue by yxmyxmyyy** [chesha1/gf2-daily-helper#2]
这是用华为测试的日志
日志
2024-06-26T08:22:26Z Start invoke request 'd49c429d-7a6b-4532-b1ab-00b24a595a16', version: latest
{ Code: -1, Message: '手机号码格式不正确', data: '' }

**Comment by chesha1** [comment]
@yxmyxmyyy 感谢反馈

因为目前的散爆账号，是不存在邮箱注册这个途径的，新注册只能用手机号，大部分人也都是手机号形式的账号，所以目前只提供了用手机号登录这一个选项

已经知道问题在哪里了，预计于一天内完成适配

**Comment by chesha1** [comment]
@yxmyxmyyy 已完成开发，请使用最新的 Release 中的文件

因为我没有邮箱账号用户用于测试，只能假设后面的行为一切不变（按理说也该不变），如果还有其他问题请再反馈

**Comment by yxmyxmyyy** [comment]
ok，这个版本可以用了
