### ISSUE TITLE
积分足够，但是未能领取全部Error: HTTP error! status: 429

### ISSUE THREAD

**Issue by weqweasd** [chesha1/gf2-daily-helper#22]
[d474c55b-bd7d-4433-9079-0db612ac1591.log](https://github.com/user-attachments/files/17806916/d474c55b-bd7d-4433-9079-0db612ac1591.log)
`{ Code: 0, Message: 'OK', data: null }`
`{ Code: 0, Message: 'OK', data: null }`
`{ Code: 0, Message: 'OK', data: null }`
`{ Code: 0, Message: 'OK', data: null }`
`{ Code: 0, Message: 'OK', data: null }`
`{ Code: 0, Message: 'OK', data: null }`
`Error: HTTP error! status: 429`
`Error: HTTP error! status: 429`
`Error: HTTP error! status: 429`
`Error: HTTP error! status: 429`
`{ Code: 0, Message: 'OK', data: {} }`
`{ Code: 30012, Message: '已达道具兑换上限', data: null }`
`2024-11-18T21:05:02Z Finish invoke request 'd474c55b-bd7d-4433-9079-0db612ac1591', duration: 1289.392ms, billing duration: 1290ms, memory used: 84.430MB, billing memory: 128MB, cpu used: 0.264U, storage used: 0.039MB`

**Comment by chesha1** [comment]
看起来是兑换物品的时候请求发得太快了，已经在 842259464287fb10e8ea84c90b43e15538750e49 中修改了，麻烦再试一下看看还会不会报错，可以手动运行一下那个 serverless 函数，或者等明天看看
